apiVersion : apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app : k8s-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      project: k8s-test
  template:
    metadata:
      labels:
        project: k8s-test
    spec:
      containers:
        - name : k8s-test--django
          image: django:django1111
          ports:
            - containerPort: 81

---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    env  : prod
    owner: VitalyKlyukin
spec:
  selector:
    project: k8s-test
  ports:
    - name       : app-listener
      protocol   : TCP
      port       : 81
      targetPort : 81
  type: ClusterIP